version: '3'
services:

  #PHP Service
  app:
    build:
    #   args:
    #     user: arzky
    #     uid: 1000
      context: .
      dockerfile: Dockerfile
    image: arzky/php
    restart: unless-stopped
    tty: true
    env_file:
      - docker.env
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
    #   - ./:/var/www
      - ./storage:/var/www/storage
      - ./docker-compose/supervisor/logs:/var/log/supervisor
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - tdc-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    #   - "443:443"
    env_file:
      - docker.env
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker-compose/nginx/logs:/var/log/nginx
    networks:
      - tdc-network

  #MySQL Service
  db:
    image: mysql:8
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_tdc
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_USER: user_tdc
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker-compose/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - tdc-network
#Docker Networks
networks:
  tdc-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
